services:
  # Container 1 do postgres, inicia apenas o servidor
  postgres:
    image: postgres:17-alpine
    container_name: portas_abertas_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # COntainer 2 do pgadmin para visualizar o banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: portas_abertas_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # container "api" para rodar o backend
  api:
    build: . # Diz ao Docker para usar o Dockerfile na mesma pasta
    container_name: portas_abertas_api
    restart: always
    ports:
      - "${PORT}:${PORT}" # Mapeia a porta do .env para sua máquina
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - DB_HOST=portas_abertas_db
      - DB_PORT=5432 # Dentro da rede do Docker, a porta do banco é a original (5432)
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres # Só vai iniciar o container da api depois do postgres

volumes:
  postgres_data:
